context:
  version: "0.23.1"

package:
  name: zola
  version: ${{ version }}

source:
  url: https://github.com/getzola/zola/archive/v${{ version }}.tar.gz
  sha256: 331240b037bbef0a15e6c1db5a2eb572097f12a362deb075a331dbb849928f83

build:
  number: 0
  skip: ppc64le

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - oniguruma
    - openssl

tests:
  - script:
      - zola --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: A fast static site generator in a single binary with everything built-in.
  homepage: https://github.com/getzola/zola
  repository: https://github.com/getzola/zola

extra:
  recipe-maintainers:
    - danielnachun
